v2 to v3 converter for survey runner
ONSdigital/eq-json-version-converter pull request #1
Opened 2019-10-10 13:39 UTC by LJBabbage

This is the initial PR for the converter. It was written to convert the e-commerce survey from v2 to v3, but development is on hold until ownership and the future of v2/v3 is decided. Because of this the bells and whistles are not all there (tests etc), but it hopefully is easy enough to understand up to this point and offers enough value for a PR

I have run it through pylint and black correcting the obvious things. Reviews are welcome, and I will correct any mistakes, but as its a little bit up in the air at the minute a thorough review is not really appropriate.

### How to run
The Readme is the best place to go.

2019-10-14 08:28 UTC, JamesGardiner requested changes
A few initial comments; I haven't gone over the code or functionality yet but the following should be fairly quick to implement:

1. A Makefile would be useful with a few initial target such as test, convert, validate etc
2. You might want to consider packaging this so it can be installed against a specific python environment with deterministic builds
3. Even though this is a helper, we should still be unit testing
4. Branch merge needs protection based on a travis build going green - this should be unit tests passing and targeted schemas passing validation I guess

2019-10-14 09:32 UTC, JamesGardiner requested changes
There are a lot of `if` statements here that could be easily removed if `get` methods used default return values or try/except blocks were used

2019-10-14 09:32 UTC, JamesGardiner commented on .gitignore
> +.idea
Worth populating this using the examples from our other python repos

2019-10-14 09:32 UTC, JamesGardiner commented on README.md
> +To use the application, firstly populate the schemas/to_convert with your v2 Survey Runner JSON, then run the command below
```suggestion
To use the application, first populate the directory  `schemas/to_convert` with your v2 Survey Runner JSON then run:
```

2019-10-14 09:32 UTC, JamesGardiner commented on README.md
> +pipenv run python app.py
```
make convert
```

2019-10-14 09:32 UTC, JamesGardiner commented on README.md
> +pipenv run python app.py
You've got pipenv commands here, so the installation section of the readme should cover installing the application into a pipenv virtual environment

2019-10-14 09:32 UTC, JamesGardiner commented on README.md
> +Results of the conversion will appear in schemas/converted
```suggestion
Results of the conversion will appear in `schemas/converted`
```

2019-10-14 09:32 UTC, JamesGardiner commented on README.md
> +pipenv run ./scripts/test_schemas_against_validator.sh
```suggestion
make validate
```

2019-10-14 09:32 UTC, JamesGardiner commented on README.md
> +If you want to test the results generated in the schema/converted folder against eq schema validator (https://github.com/ONSdigital/eq-schema-validator) use the following command
```suggestion
If you want to test the results generated in the schema/converted folder against eq schema validator (https://github.com/ONSdigital/eq-schema-validator) use:
```

2019-10-14 09:32 UTC, JamesGardiner commented on app.py
> +from app.converter import Converter
```suggestion
from app import Converter
```

I'd hoist Converter inside the app's `__init__`

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +        with open("schemas/to_convert/" + file_name, encoding="utf8") as schema_data:
```suggestion
        with open("schemas/to_convert/" + file_name, 'r', encoding="utf8") as file:
```
The context manager is a file handler not the actual data

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +            self.schema = load(schema_data)
```suggestion
            self.schema = load(file)
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +        with open("schemas/converted/" + self.file_name, "w") as json_file:
```suggestion
        with open("schemas/converted/" + self.file_name, "w") as file:
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +from app.rules.v2_to_v3.routing_rules import routing_conversions
These should go in to a conversions module or get imported from the `v2_to_v3` module - it will make this import block more readable.

It would then be:
`from app.rules.v2_to_v3 import conversions`

Then access the methods:
`conversions.routing_conversions()` etc.

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +                self.schema, json_file, sort_keys=True, indent=4, separators=(",", ": ")
Is 4 our standard for json indentation? I thought we use `prettier.js` which defaults to 2? Might actually be worth having a js formatter run on it using `make format` in any case.

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +
```suggestion
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +    def convert_schema(self):
This would work well as the class callable

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +from json import load, dump
Looking at his class I'd actually remove the `__init__` method, throw everything into a callable, instantiate at the module level then import it and use it as a function - saves on instantiating a new instance on every run

2019-10-14 09:32 UTC, JamesGardiner commented on app/converter.py
> +from json import load, dump
```
from app import convert

for file in dirs:
    convert(file)
```

Have it do the conversion and the save as part of the `__call__` method

2019-10-14 09:32 UTC, JamesGardiner commented on app/helpers/parse_schema.py
> +        return OrderedDict(
Assuming Python3.7 do you really need  `OrderedDict`?

2019-10-14 09:32 UTC, JamesGardiner commented on app/helpers/parse_schema.py
> +    nested_objects = OrderedDict()
Again, I don't think an OrderedDict is necessary here given Py3.7 will preserve order

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/routing_rules.py
> +            if whens:
this if isn't needed

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/routing_rules.py
> +    if "routing_rules" in item:
```suggestion
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/routing_rules.py
> +        for rule in item["routing_rules"]:
```suggestion
        for rule in item.get("routing_rules", []):
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/routing_rules.py
> +            whens = rule.get("goto").get("when")
```suggestion
            whens = rule.get("goto", {}).get("when")
```

Don't chain two `get` methods without defaulting to an object that implements it in the first call.

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/routing_rules.py
> +                    answer = schema.get_answer(when.get("id"))
```suggestion
                    answer = schema.get_answer(when.get("id", {}))
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +    if "title" in question:
```suggestion
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +        question_title = question["title"]
```suggestion
try:
    question_title = question["title"]
except KeyError:
    return None
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +        question_title = question["title"]
Make this the first call so it returns before the placeholders list is instantiated if necessary

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +            if pattern.get("pattern") in question_title:
This will break with a `TypeError` if the pattern.get returns None

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +            if pattern.get("pattern") in question_title:
```suggestion
            try:
                pattern = placeholder['pattern']
            except KeyError:
                break
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +        for pattern in placeholders_to_replace:
```suggestion
        for placeholder in placeholders_to_replace:
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +                    question_title, pattern.get("pattern")
```suggestion
                    question_title, pattern
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +                    pattern_matches_in_title, question_title, pattern.get("pattern")
```suggestion
                    pattern_matches_in_title, question_title, pattern
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +    placeholders = []
```suggestion
    return [{"placeholder": match.replace("-", "_"), "value": {"identifier": match, "source": source}} for match in pattern_matches_in_title]
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +    if "definitions" in question:
```suggestion
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +        for definition in question["definitions"]:
```suggestion
    for definition in question.get("definitions", []):
```

2019-10-14 09:32 UTC, JamesGardiner commented on app/rules/v2_to_v3/question_conversions.py
> +            rename_content_key(definition)
```suggestion
        rename_content_key(definition)
```

2019-10-14 09:32 UTC, JamesGardiner requested changes
There are a lot of `if` statements here that could be easily removed if `get` methods used default return values or try/except blocks were used.

I've marked a few with suggestions but didnt do all of them

2019-10-17 11:31 UTC, ajmaddaford commented
Adding a `.python-version` file would be useful.

2019-10-23 14:26 UTC, JamesGardiner requested changes

2019-10-23 14:26 UTC, JamesGardiner commented on .pylintrc
> +jobs=1
```suggestion
jobs=0
```

Will use all cores for speed

2019-10-23 14:26 UTC, JamesGardiner commented on README.md
> +pipenv shell
`make build` ?

2019-10-23 14:26 UTC, JamesGardiner commented on .python-version
> +3.7.4
https://docs.python.org/3/whatsnew/3.8.html ?

2019-10-23 14:26 UTC, JamesGardiner commented on README.md
> +This repository has been written to convert v2 Survey Runner JSON (https://github.com/ONSdigital/eq-survey-runner) to v3.
```suggestion
This repository has been written to convert [Survey Runner](https://github.com/ONSdigital/eq-survey-runner) schemas from v2 to v3.
```

2019-10-23 14:26 UTC, JamesGardiner commented on README.md
> +N.B This was written for the e-commerce survey, so although it might convert some other v2 surveys they might not pass validation.
```suggestion
N.B Only e-commerce surveys are currently supported. Other surveys may convert, but aren't guaranteed to be valid to the v3 specification.
```

2019-10-23 14:26 UTC, JamesGardiner commented on README.md
> +This application uses pipenv, please follow the following steps.
```suggestion
To intall, run the following:
```

2019-10-23 14:26 UTC, JamesGardiner commented on README.md
> +pipenv shell
We shouldn't need to ask the user to enter into a new shell to complete the conversion

2019-10-23 14:26 UTC, JamesGardiner commented on README.md
> +To use the application, first populate the directory  `schemas/to_convert` with your v2 Survey Runner JSON then run:
```suggestion
Put any v2 schema you want converted into the directory `schemas/to_convert`
```

2019-10-24 10:21 UTC, JamesGardiner approved these changes

2019-10-24 14:30 UTC, ajmaddaford approved these changes
It works 🙂

2019-10-24 14:30 UTC, ajmaddaford approved these changes
It works 🙂

2019-10-25 08:37 UTC, merged